### ISSUE TITLE
Format for input cubes

### ISSUE THREAD

**Issue by wjcramer** [PhangsTeam/pycprops#15]
Hi,

I'd very much like to use the pycprops package for my ALMA data and am looking for a few tips as its crashing currently. What are the desired units and format of the input cube? Should the polarization axis be trimmed? Does it need to be frequency, or velocity, and does it matter if it's Jansky or Kelvin? Furthermore I'm currently getting a crash saying my cube is too large (3 Gb) to load into memory, strangely this seems to be resolved if I specify a noise cube. What are the preferred units for the noise cube?

Thanks!

**Comment by wjcramer** [comment]
Just for clarity, this is the current error I'm getting using a cube with velocity as the spectral axis.

`File /opt/anaconda3/lib/python3.9/site-packages/pycprops-0.3.dev13+g1061680-py3.9.egg/pycprops/pycprops.py:66, in fits2props(cube_file, datadir, output_directory, mask_file, noise_file, distance, asgnname, propsname, delta, verbose, alphaCO, channelcorr, allow_huge, asgn, **kwargs)
     63 s = s.with_mask(mask)
     65 if asgn is None:
---> 66     asgn = cube_decomp(s, delta=delta, verbose=verbose,
     67                        **kwargs)
     68     asgn.writeto(output_directory + '/' + asgnname, overwrite=True)
     70 props = cloudalyze(s, asgn.data,
     71                    distance=distance,
     72                    verbose=verbose,
   (...)
     75                    channelcorr=channelcorr,
     76                    **kwargs)

File /opt/anaconda3/lib/python3.9/site-packages/pycprops-0.3.dev13+g1061680-py3.9.egg/pycprops/decomposition.py:115, in cube_decomp(s, minpix, delta, specfriends, friends, compactness, method, sigdiscont, verbose, **kwargs)
    112 meta['vaxis'] = 0
    113 meta['wcs'] = s.wcs
--> 115 lam = np.median(s.with_spectral_unit(u.mm,
    116                                      velocity_convention='radio').spectral_axis)
    117 meta['wavelength'] = lam
    119 wslabel = np.zeros(s.shape, dtype=np.int)    

File /opt/anaconda3/lib/python3.9/site-packages/spectral_cube/spectral_cube.py:1293, in BaseSpectralCube.with_spectral_unit(self, unit, velocity_convention, rest_value)
   1269 def with_spectral_unit(self, unit, velocity_convention=None,
   1270                        rest_value=None):
   1271     """
   1272     Returns a new Cube with a different Spectral Axis unit
   1273 
   (...)
   1291 
   1292     """
-> 1293     newwcs,newmeta = self._new_spectral_wcs(unit=unit,
   1294                                             velocity_convention=velocity_convention,
   1295                                             rest_value=rest_value)
   1297     if self._mask is not None:
   1298         newmask = self._mask.with_spectral_unit(unit,
   1299                                                 velocity_convention=velocity_convention,
   1300                                                 rest_value=rest_value)

File /opt/anaconda3/lib/python3.9/site-packages/spectral_cube/base_class.py:334, in SpectralAxisMixinClass._new_spectral_wcs(self, unit, velocity_convention, rest_value)
    331     meta['Original Unit'] = self._wcs.wcs.cunit[self._wcs.wcs.spec]
    332     meta['Original Type'] = self._wcs.wcs.ctype[self._wcs.wcs.spec]
--> 334 out_ctype = ctype_from_vconv(self._wcs.wcs.ctype[self._wcs.wcs.spec],
    335                              unit,
    336                              velocity_convention=velocity_convention)
    338 newwcs = convert_spectral_axis(self._wcs, unit, out_ctype,
    339                                rest_value=rest_value)
    341 newwcs.wcs.set()

File /opt/anaconda3/lib/python3.9/site-packages/spectral_cube/spectral_axis.py:119, in determine_ctype_from_vconv(ctype, unit, velocity_convention)
    117 else:
    118     lin_cunit = LINEAR_CUNIT_DICT[ctype]
--> 119     in_physchar = PHYSICAL_TYPE_TO_CHAR[lin_cunit.physical_type]
    121 if unit.physical_type == 'speed':
    122     if velocity_convention is None and ctype[0] == 'V':
    123         # Special case: velocity <-> velocity doesn't care about convention

KeyError: PhysicalType('frequency')
`

**Comment by low-sky** [comment]
Thanks for identifying this issue. Would you be willing to post (part of) the header associated with the file?  It looks like the header is missing some information that's required for a unit conversion.  In particular, I'd guess that the rest frequency (`RESTFRQ` or `RESTFREQ`) isn't set.

**Comment by wjcramer** [comment]
Thanks very much for your help! The header of my file is here, it does look like the RESTFREQ is set. Also an additional note that I'm using the 3D mask and noise cube produced by https://github.com/tonywong94/maskmoment , not sure if this something that you may have used for this purpose before:

SIMPLE  =                    T /Standard FITS                                   
BITPIX  =                  -32 /Floating point (32 bit)                         
NAXIS   =                    3                                                  
NAXIS1  =                 2916                                                  
NAXIS2  =                 2916                                                  
NAXIS3  =                   81                                                  
EXTEND  =                    T                                                  
BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 
BZERO   =   0.000000000000E+00                                                  
BMAJ    =   1.355170235313E-04                                                  
BMIN    =   9.524119640717E-05                                                  
BPA     =  -3.829994763770E+01                                                  
BTYPE   = 'Intensity'                                                           
OBJECT  = 'GMP2910 '                                                            
BUNIT   = 'Jy/beam '           /Brightness (pixel) unit                         
EQUINOX =   2.000000000000E+03                                                  
RADESYS = 'FK5     '                                                            
LONPOLE =   1.800000000000E+02                                                  
LATPOLE =   2.787194444444E+01                                                  
PC1_1   =   1.000000000000E+00                                                  
PC2_1   =   0.000000000000E+00                                                  
PC3_1   =   0.000000000000E+00                                                  
PC1_2   =   0.000000000000E+00                                                  
PC2_2   =   1.000000000000E+00                                                  
PC3_2   =   0.000000000000E+00                                                  
PC1_3   =   0.000000000000E+00                                                  
PC2_3   =   0.000000000000E+00                                                  
PC3_3   =   1.000000000000E+00                                                  
CTYPE1  = 'RA---SIN'                                                            
CRVAL1  =   1.950487500000E+02                                                  
CDELT1  =  -1.666666666667E-05                                                  
CRPIX1  =   1.459000000000E+03                                                  
CUNIT1  = 'deg     '                                                            
CTYPE2  = 'DEC--SIN'                                                            
CRVAL2  =   2.787194444444E+01                                                  
CDELT2  =   1.666666666667E-05                                                  
CRPIX2  =   1.459000000000E+03                                                  
CUNIT2  = 'deg     '                                                            
CTYPE3  = 'VRAD    '                                                            
CRVAL3  =  -1.000000000000E+05                                                  
CDELT3  =   5.000000000005E+03                                                  
CRPIX3  =   1.000000000000E+00                                                  
CUNIT3  = 'm/s     '                                                            
PV2_1   =   0.000000000000E+00                                                  
PV2_2   =   0.000000000000E+00                                                  
RESTFRQ =   2.265217690000E+11 /Rest Frequency (Hz)                             
SPECSYS = 'LSRK    '           /Spectral reference frame                        
ALTRVAL =   2.265973285289E+11 /Alternate frequency reference value             
ALTRPIX =   1.000000000000E+00 /Alternate frequency reference pixel             
VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio                 
COMMENT casacore non-standard usage: 4 LSD, 5 GEO, 6 SOU, 7 GAL                 
TELESCOP= 'ALMA    '                                                            
OBSERVER= 'wcramer '                                                            
DATE-OBS= '2020-03-02T07:01:02.544001'                                          
TIMESYS = 'UTC     '                                                            
OBSRA   =   1.950487500000E+02                                                  
OBSDEC  =   2.787194444444E+01                                                  
OBSGEO-X=   2.225142180269E+06                                                  
OBSGEO-Y=  -5.440307370349E+06                                                  
OBSGEO-Z=  -2.481029851874E+06                                                  
INSTRUME= 'ALMA    '                                                            
DISTANCE=   0.000000000000E+00                                                  
USEWEIGH=                    T                                                  
DATE    = '2022-08-25T16:58:09.851881' /Date FITS file was written              
ORIGIN  = 'CASA 6.1.1-15 CASAtools:v1.0.0'                                      
HISTORY CASA START LOGTABLE                                                     
HISTORY 2022-08-25T16:58:08 INFO SRCCODE='::imsubimage'                         
HISTORY version: 6.1.1-15 CASAtools:v1.0.0                                      
HISTORY 2022-08-25T16:58:08 INFO SRCCODE='::imsubimage'                         
HISTORY imsubimage(imagename="D100_combine_CO_cube.image.pbcor", outfile="D100_c
HISTORY >ombine_CO_cube_trim.image", box="", region="", chans="", stokes="", mas
HISTORY >="", dropdeg=True, overwrite=True, verbose=True, stretch=False, keepaxe
HISTORY >=[])                                                                   
HISTORY CASA END LOGTABLE                                                       
END

**Comment by low-sky** [comment]
I think this an underlying update that happened in astropy that prompted changes in SpectralCube.  I was able to reproduce this from your header but then resolved it by upgrading SpectralCube to >=0.6.0.

**Comment by wjcramer** [comment]
Thanks again, upgrading to spectral-cube 0.6.0 does seem to get me past that issue. I'm still getting a crash however with the error:

---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
Cell In [4], line 1
----> 1 pycprops.fits2props(cubefile,
      2                     mask_file=mask,
      3                     noise_file=noise,
      4                     distance=d,               
      5                     asgnname='mycube.asgn.fits',
      6                     propsname='mycube.props.fits')

File /opt/anaconda3/lib/python3.9/site-packages/pycprops-0.3.dev13+g1061680-py3.9.egg/pycprops/pycprops.py:70, in fits2props(cube_file, datadir, output_directory, mask_file, noise_file, distance, asgnname, propsname, delta, verbose, alphaCO, channelcorr, allow_huge, asgn, **kwargs)
     66     asgn = cube_decomp(s, delta=delta, verbose=verbose,
     67                        **kwargs)
     68     asgn.writeto(output_directory + '/' + asgnname, overwrite=True)
---> 70 props = cloudalyze(s, asgn.data,
     71                    distance=distance,
     72                    verbose=verbose,
     73                    noise=noise,
     74                    alphaCO=alphaCO,
     75                    channelcorr=channelcorr,
     76                    **kwargs)
     78 props.write(output_directory + '/' + propsname, overwrite=True)

File /opt/anaconda3/lib/python3.9/site-packages/pycprops-0.3.dev13+g1061680-py3.9.egg/pycprops/cloudalyze.py:194, in cloudalyze(cube, label, distance, alphaCO, extrapolate, bootstrap, rmstorad, noise, verbose, channelcorr, **kwargs)
    192 cloudlist = []
    193 spectral_unit = cube.spectral_axis
--> 194 dv = np.abs((cube.spectral_axis[1] 
    195              - cube.spectral_axis[0]).to(u.km / u.s).value)
    196 apix_sr =(np.abs(np.linalg.det(cube.wcs.celestial.pixel_scale_matrix)) 
    197           * u.deg**2).to(u.sr)
    198 pixscale = np.sqrt(np.abs(np.linalg.det(
    199     cube.wcs.celestial.pixel_scale_matrix))) * u.deg

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/quantity.py:846, in Quantity.to(self, unit, equivalencies, copy)
    842 unit = Unit(unit)
    843 if copy:
    844     # Avoid using to_value to ensure that we make a copy. We also
    845     # don't want to slow down this method (esp. the scalar case).
--> 846     value = self._to_value(unit, equivalencies)
    847 else:
    848     # to_value only copies if necessary
    849     value = self.to_value(unit, equivalencies)

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/quantity.py:800, in Quantity._to_value(self, unit, equivalencies)
    797     equivalencies = self._equivalencies
    798 if not self.dtype.names or isinstance(self.unit, StructuredUnit):
    799     # Standard path, let unit to do work.
--> 800     return self.unit.to(unit, self.view(np.ndarray),
    801                         equivalencies=equivalencies)
    803 else:
    804     # The .to() method of a simple unit cannot convert a structured
    805     # dtype, so we work around it, by recursing.
    806     # TODO: deprecate this?
    807     # Convert simple to Structured on initialization?
    808     result = np.empty_like(self.view(np.ndarray))

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/core.py:1130, in UnitBase.to(self, other, value, equivalencies)
   1128     return UNITY
   1129 else:
-> 1130     return self._get_converter(Unit(other),
   1131                                equivalencies=equivalencies)(value)

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/core.py:1061, in UnitBase._get_converter(self, other, equivalencies)
   1058             except Exception:
   1059                 pass
-> 1061 raise exc

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/core.py:1046, in UnitBase._get_converter(self, other, equivalencies)
   1044 # if that doesn't work, maybe we can do it with equivalencies?
   1045 try:
-> 1046     return self._apply_equivalencies(
   1047         self, other, self._normalize_equivalencies(equivalencies))
   1048 except UnitsError as exc:
   1049     # Last hope: maybe other knows how to do it?
   1050     # We assume the equivalencies have the unit itself as first item.
   1051     # TODO: maybe better for other to have a `_back_converter` method?
   1052     if hasattr(other, 'equivalencies'):

File /opt/anaconda3/lib/python3.9/site-packages/astropy/units/core.py:1022, in UnitBase._apply_equivalencies(self, unit, other, equivalencies)
   1019 unit_str = get_err_str(unit)
   1020 other_str = get_err_str(other)
-> 1022 raise UnitConversionError(
   1023     f"{unit_str} and {other_str} are not convertible")

UnitConversionError: 'Hz' (frequency) and 'km / s' (speed/velocity) are not convertible

**Comment by wjcramer** [comment]
Thanks very much, that did indeed solve it and everything runs fine now! SpectralCube >=0.6.0 was not available through anaconda, but I did manage a pip install for anyone else with the same issue that reads this.
