### ISSUE TITLE
Current README example would not find noise_file

### ISSUE THREAD

**Issue by nbrunett** [PhangsTeam/pycprops#2]
Currently the README gives the following example for running `fits2props`

```python
import pycprops
import astropy.units as u
cubefile = 'mycube.fits'  # Your cube
mask = 'mycube.mask.fits' # Mask defining where to find emission
d = 8.0 * u.kpc           # Distance (with units)

pycprops.fits2props(cubefile,
                    mask_file=mask,
                    distance=d,               
                    asgnname='mycube.asgn.fits',
                    propsname='mycube.props.fits')
```

but since the default value of the `noise_file` argument is `None` this example crashes with

```
File "/cavern/home/brunettn/bin/miniconda3/envs/research/lib/python3.7/site-packages/pycprops-0.1.dev20+g52aad10-py3.7.egg/pycprops/pycprops.py", line 40, in fits2props
    noise = SpectralCube.read(datadir + '/' +noise_file)
TypeError: can only concatenate str (not "NoneType") to str
```

The example should be updated to show all of the mandatory arguments, but `fits2props` should also be changed to give a more descriptive error about what is actually wrong (maybe there shouldn't be a default value for that and other arguments).

**Comment by low-sky** [comment]
Addressed in 7b378aa by allowing calculation without noise file.
