### ISSUE TITLE
ProgressBar not closed properly in cloudalzye

### ISSUE THREAD

**Issue by nbrunett** [PhangsTeam/pycprops#3]
The Astropy ProgressBar in the cloudalyze function works as the loop is running, but it does not finish by reporting the total runtime for the loop and adding a newline. This seems to be because the ProgressBar object is not closed/released properly at the end of the loop. Instead of line 212 and 213 which are

```python
if verbose:
    bar = ProgressBar(len(uniqlabels))
```

the entire loop block (down to and including the current line 408) should be within a `with` statement like

```python
    if verbose:
        barfile = None
    else:
        barfile = open(os.devnull, 'w')
    with ProgressBar(len(uniqlabels), file=barfile) as bar:
        for cloudnum, thislabel in enumerate(uniqlabels):
#
# ...snip...
#
            cloudlist += [thiscloud]
            if verbose:
                bar.update()
            else:
                barfile.close()
    outtable = Table(cloudlist)
    return(outtable)
```

When the ProgressBar file is `None` then it sends its output to the terminal. Otherwise we just send the output to the void. I think this also sets some of the groundwork for saving log files which could include the runtime of these steps by swapping out `os.devnull` for the log file.

**Comment by low-sky** [comment]
Addressed in 259584d
