### ISSUE TITLE
Current mask-handling includes pixels set to NaN

### ISSUE THREAD

**Issue by nbrunett** [PhangsTeam/pycprops#4]
I found that if I passed a FITS cube for the mask that had NaN pixels where I did not want the algorithms to work and float values where I did want it to work, then all pixels were included in processing. I believe it had to do with this line in pycprops.py

```Python
s = s.with_mask(mask.astype(np.bool))
```

where casting `np.nan` to `bool` results in `True`. I'm not sure if it's a Numpy version issue, but I can give some more info on my environment later if it would help. Sorry this is a bit terse, I wanted to bring this to your attention before I forgot (and I'm taking some time off the rest of this week).

**Comment by low-sky** [comment]
Addressed in 259584d (?)

**Comment by nbrunett** [comment]
Looks good to me.
